version: "3"

tasks:
  sb-up:
    cmds:
      - npx supabase start

  sb-reset:
    cmds:
      - npx supabase db reset

  sb-migration-add:
    cmds:
      - npx supabase migration new {{.CLI_ARGS}}

  sb-migration-up:
    dotenv: [".env.{{.CLI_ARGS}}", ".env.local"]
    cmds:
      - npx supabase migration up --db-url $SUPABASE_DB_URL

  sb-link:
    dotenv: [".env.dev"]
    cmds:
      - npx supabase link -p $SUPABASE_DB_PASS --project-ref $SUPABASE_PROJECT_ID

  sb-fndeploy:
    dotenv: [".env.{{.CLI_ARGS}}", ".env.local"]
    cmds:
      - npx supabase functions deploy

  front-up:
    dotenv: [".env.{{.CLI_ARGS}}", ".env.local"]
    cmds:
      - deno task f:dev

  front-prev:
    dotenv: [".env.preview"]
    cmds:
      - deno task f:build
      - deno task f:prev

  db-client:
    dotenv: [".env.local"]
    cmds:
      - deno task db:client

  gql-client:
    cmds:
      - deno task gql:client

  add-ui:
    cmds:
      - deno task add:shadcn {{.CLI_ARGS}}

  mw-update:
    cmds:
      - deno task --recursive mw:update

  mw-update:f:
    cmds:
      - deno task --recursive mw:update:f
