version: "3"

vars:
  GREETING: Hello, World!

tasks:
  sb-up:
    cmds:
      - npx supabase start

  sb-reset:
    cmds:
      - npx supabase db reset

  sb-migration-add:
    cmds:
      - npx supabase migration new {{.CLI_ARGS}}

  sb-migration-up:
    cmds:
      - npx supabase migration up {{.CLI_ARGS}}

  sb-pull:
    dotenv: [".env.local"]
    cmds:
      - deno task db:pull

  sb-link:
    dotenv: [".env.dev"]
    cmds:
      - npx supabase link -p $SUPABASE_DB_PASS --project-ref $SUPABASE_PROJECT_ID

  sb-fndeploy:
    dotenv: [".env.dev"]
    cmds:
      - npx supabase functions deploy

  front-up:
    cmds:
      - deno task f:dev
